### ISSUE TITLE
Quilt?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [fonnymunkey/BetterTabs#2]
Just wondering if you plan on supporting quilt.

I know most fabric mods work on quilt, it's just that when downloading them from a client it makes it more of a hassle if it isn't shown there and having to look for the mod on your browser and download it from there and manually moving to the mods folder rather than from the client. Also makes updating a hassle

If you don't plan on supporting/updating to quilt that's also fine.

**Comment by fonnymunkey** [comment]
This mod doesn't exist on versions with Fabric, much less Quilt, if it ever gets updated to newer versions then it will be but as it was made for a specific modpack that is unlikely until the pack updates as well.

**Comment by Aces-and-Jacks** [comment]
Sorry I think I got the wrong mod. Had a similar name so mixed it up
